name: Validate image naming convention

on:
  push:
    branches:
      - main
    paths:
      - "img/**"
  pull_request:
    paths:
      - "img/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check naming convention
        run: bash validate.sh
